package main

import (
	"github.com/gin-gonic/gin"
	"github.com/swaggo/gin-swagger"
	"github.com/swaggo/gin-swagger/swaggerFiles"
	_ "./docs" // docs is generated by Swag CLI, you have to import it.
)

func main() {
	r := gin.New()

	url := ginSwagger.URL("http://0.0.0.0:3004/swagger/doc.json") //The url pointing to API definition
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))

	//r.Run()
	r.Run(":3004")
}
