version: "3"
services:
  go:
    build: backend_go
    image: back_go
    working_dir: /go/src/github.com/proyecto/backend_go
    restart: on-failure
    command: fresh
    ports:
      - "8090:8090"
    volumes:
      - /go/src/github.com/proyecto/backend_go/common
        